### ISSUE TITLE
Android Studio: [!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-plugins-0.4.1`

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#213]
Using Android Studio I get the following error running ``j2objcXcode`` task:

```
:shared:j2objcXcode
[33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
Consider adding the following to ~/.profile:
export LANG=en_US.UTF-8
[0m
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-plugins-0.4.1`
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-0.4.3`
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.0`
[!] The version of CocoaPods used to generate the lockfile (0.37.2) is higher than the version of the current executable (0.36.0). Incompatibility issues may arise.
Analyzing dependencies
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface/error_report.rb:119:in ``': No such file or directory - git (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface/error_report.rb:119:in `git_information'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface/error_report.rb:38:in `report'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:59:in `report_error'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:374:in `handle_exception'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:315:in `rescue in run'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:303:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
	from /usr/bin/pod:23:in `load'
	from /usr/bin/pod:23:in `<main>'
Error:Execution failed for task ':shared:j2objcXcode'.
> Process 'command 'pod'' finished with non-zero exit value 1
Information:BUILD FAILED
```

**Comment by confile** [comment]
@advayDev1 This is a similar error than I have with eclipse. Do you have any idea why Android Studio is using another version of cocoapods than my command line? Command line version which is 0.37.0?

**Comment by confile** [comment]
Just running in in sudo mode. This works.

**Comment by advayDev1** [comment]
I had no idea Android Studio integrates with Cocoapods in anyway.  My only assumption is that the environment variables in Android Studio are not the same as in your terminal.  I suggest dumping the environment from Android Studio and from your regular Mac terminal and running a diff.

Also I don't use Android Studio, just IntelliJ/IDEA directly.  I also don't use pods =)

**Comment by confile** [comment]
Okay it works when I run the IDE in sudo. I have no other idea so I close this issue.

**Comment by advayDev1** [comment]
Ok, for your own benefit, I suggest dumping the environment via the terminal tool window inside Android Studio.  It may help you debug this.

**Comment by advayDev1** [comment]
(as in do it for a sudo instance, and a non-sudo instnace and compare them)

**Comment by confile** [comment]
@advayDev1 How do I do that?

**Comment by advayDev1** [comment]
Type `env` in the Android Studio tool window[1]   in both a non-sudo Android Studio and an Android Studio.

[1] https://www.jetbrains.com/idea/help/working-with-embedded-local-terminal.html

**Comment by confile** [comment]
I checked this both versions had the correct cocoapods version on the class path. There is no reference to the old version 0.36 anywere.

Lts pause here with this issue it takes to much time and the sudo workaround still works fine.
