### ISSUE TITLE
Could not find method translateJ2objcLibs() for arguments on root project

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#258]
- j2objc plugin version commit "Merge pull request #253 from j2objc-contrib/release_v0.3.0-alpha" commit 556edca1ccbaaaf8951a1e78b935175a6064c080

- setup: two projects majestella-base, majestella-main. 

[majestella-base build.gradle](https://gist.github.com/confile/bfadfdc00fc7ef85fd90)
[majestella-main build.gradle](https://gist.github.com/confile/594fb533a30166405e76)
[majestella-main settings.gradle](https://gist.github.com/confile/ed4a4b29ecbf8b24ace0)

there is no root project or root build.gradle

running ``./gradlew clean --no-daemon --stacktrace`` leads to the following error: 

```
 ./gradlew clean --no-daemon --stacktrace
Project 'majestella-main' is missing finalConfigure():
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/FAQ.md#How-do-I-call-finalConfigure

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/majestella-main/build.gradle' line: 115

* What went wrong:
A problem occurred evaluating root project 'majestella-main'.
> Could not find method translateJ2objcLibs() for arguments [j2objc_annotations.jar, j2objc_guava.jar, javax.inject-1.jar, jsr305-3.0.0.jar] on root project 'majestella-main'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'majestella-main'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:76)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(DefaultScriptPluginFactory.java:148)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:156)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:487)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:85)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.api.internal.MissingMethodException: Could not find method translateJ2objcLibs() for arguments [j2objc_annotations.jar, j2objc_guava.jar, javax.inject-1.jar, jsr305-3.0.0.jar] on root project 'majestella-main'.
	at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
	at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:175)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_6jaiihyu4lnu78ywb4x7it7j5$_run_closure5.doCall(/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/majestella-main/build.gradle:115)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
	at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
	at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_6jaiihyu4lnu78ywb4x7it7j5.run(/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/majestella-main/build.gradle:92)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:74)
	... 38 more


BUILD FAILED
```

**Comment by confile** [comment]
@advayDev1 I provide you more details. Hope this helps.

**Comment by confile** [comment]
@brunobowden should be added to schedule for 0.4 release

**Comment by brunobowden** [comment]
Note that `translateJ2objcLibs` is a variable and NOT a function call. As such, you can assign to it `translateJ2objcLibs = ...` but you can't call it `translateJ2objcLibs(...)`. In your example without the brackets, you're attempting a function call that doesn't work. If the following works, then please close the issue:

translateJ2objcLibs = ["j2objc_annotations.jar", "j2objc_guava.jar", "javax.inject-1.jar", "jsr305-3.0.0.jar"]

Better yet, remove the translateJ2objcLibs and it'll just work by default without you needing to do anything. You can see that it's a List<String> variable and not a method by looking at J2objcConfig.java:

![screen shot 2015-07-01 at 5 00 51 pm](https://cloud.githubusercontent.com/assets/679339/8467439/1aaf02a6-2013-11e5-9bb9-7f23432769ce.png)

**Comment by brunobowden** [comment]
If this works, then please expand the docs comment on line 166 in J2objcConfig to give an example of how to use it. Most of the time though, you shouldn't need to alter this setting at all.

**Comment by brunobowden** [comment]
Actually, I'm closing this but reopen if it's still an issue.

**Comment by brunobowden** [comment]
I think it may also work with this:

translateJ2objcLibs ["j2objc_annotations.jar", "j2objc_guava.jar", "javax.inject-1.jar", "jsr305-3.0.0.jar"]

Though again, best to drop this line entirely and then use the automatic settings which will work for you.

**Comment by confile** [comment]
@brunobowden Thanks it it fixed and you are right I will drop the line. PR is comming.
