### ISSUE TITLE
clang: error: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk'

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#259]
- j2objc plugin version commit "Merge pull request #253 from j2objc-contrib/release_v0.3.0-alpha" commit 556edca1ccbaaaf8951a1e78b935175a6064c080

- setup: two projects majestella-base, majestella-main. 

[majestella-base build.gradle](https://gist.github.com/confile/bfadfdc00fc7ef85fd90)
[majestella-main build.gradle](https://gist.github.com/confile/594fb533a30166405e76) I removed the following line from the build-gradle 

```
translateJ2objcLibs "j2objc_annotations.jar", "j2objc_guava.jar", "javax.inject-1.jar", "jsr305-3.0.0.jar"
```

[majestella-main settings.gradle](https://gist.github.com/confile/ed4a4b29ecbf8b24ace0)

there is no root project or root build.gradle

running ``./gradlew j2objcXcode --no-daemon --stacktrace`` leads to the following error: 

```
./gradlew j2objcXcode --no-daemon --stacktrace
:addAptCompilerArgs
:majestella-base:compileJava
:majestella-base:processResources UP-TO-DATE
:majestella-base:classes
:majestella-base:jar
:compileJava
:processResources
:classes
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:majestella-base:compileTestJava UP-TO-DATE
:majestella-base:processTestResources UP-TO-DATE
:majestella-base:testClasses UP-TO-DATE
:majestella-base:test UP-TO-DATE
:majestella-base:j2objcPreBuild UP-TO-DATE
:majestella-base:j2objcCycleFinder SKIPPED
:majestella-base:j2objcTranslate
:majestella-base:compileIos_arm64DebugMajestella-base-j2objcSharedLibraryMajestella-base-j2objcObjc SKIPPED
:majestella-base:linkIos_arm64DebugMajestella-base-j2objcSharedLibrary SKIPPED
:majestella-base:ios_arm64DebugMajestella-base-j2objcSharedLibrary SKIPPED
:majestella-base:compileIos_arm64DebugMajestella-base-j2objcStaticLibraryMajestella-base-j2objcObjc
clang: error: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk'

clang: error: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk'

clang: error: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk'

clang: error: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk'

clang: error: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk'

clang: error: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk'

clang: error: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk'

clang: error: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk'

clang: error: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk'

clang: error: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk'

...output for 64 more failed operation(s) continued in file:///Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/majestella-base/build/tmp/compileIos_arm64DebugMajestella-base-j2objcStaticLibraryMajestella-base-j2objcObjc/output.txt.
:majestella-base:compileIos_arm64DebugMajestella-base-j2objcStaticLibraryMajestella-base-j2objcObjc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':majestella-base:compileIos_arm64DebugMajestella-base-j2objcStaticLibraryMajestella-base-j2objcObjc'.
> Multiple build operations failed.
      Objective-C compiler failed while compiling BTimer.m.
      Objective-C compiler failed while compiling NameToken.m.
      Objective-C compiler failed while compiling ProxyStandard.m.
      Objective-C compiler failed while compiling AbstractBEvent.m.
      Objective-C compiler failed while compiling BEvent.m.
      Objective-C compiler failed while compiling ContentSlot.m.
      Objective-C compiler failed while compiling BaseParameterConfig.m.
      Objective-C compiler failed while compiling BTimerCallback.m.
      Objective-C compiler failed while compiling BSimpleEventBus.m.
      Objective-C compiler failed while compiling BUmbrellaException.m.
      ...and 64 more failures.
  See the complete log at: file:///Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/majestella-base/build/tmp/compileIos_arm64DebugMajestella-base-j2objcStaticLibraryMajestella-base-j2objcObjc/output.txt

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':majestella-base:compileIos_arm64DebugMajestella-base-j2objcStaticLibraryMajestella-base-j2objcObjc'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.internal.operations.MultipleBuildOperationFailures: Multiple build operations failed.
    Objective-C compiler failed while compiling BTimer.m.
    Objective-C compiler failed while compiling NameToken.m.
    Objective-C compiler failed while compiling ProxyStandard.m.
    Objective-C compiler failed while compiling AbstractBEvent.m.
    Objective-C compiler failed while compiling BEvent.m.
    Objective-C compiler failed while compiling ContentSlot.m.
    Objective-C compiler failed while compiling BaseParameterConfig.m.
    Objective-C compiler failed while compiling BTimerCallback.m.
    Objective-C compiler failed while compiling BSimpleEventBus.m.
    Objective-C compiler failed while compiling BUmbrellaException.m.
    ...and 64 more failures.
See the complete log at: file:///Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/majestella-base/build/tmp/compileIos_arm64DebugMajestella-base-j2objcStaticLibraryMajestella-base-j2objcObjc/output.txt
	at org.gradle.internal.operations.DefaultBuildOperationQueue.waitForCompletion(DefaultBuildOperationQueue.java:72)
	at org.gradle.nativeplatform.toolchain.internal.NativeCompiler.execute(NativeCompiler.java:73)
	at org.gradle.nativeplatform.toolchain.internal.NativeCompiler.execute(NativeCompiler.java:39)
	at org.gradle.nativeplatform.toolchain.internal.OutputCleaningCompiler.compileSources(OutputCleaningCompiler.java:46)
	at org.gradle.nativeplatform.toolchain.internal.OutputCleaningCompiler.execute(OutputCleaningCompiler.java:38)
	at org.gradle.nativeplatform.toolchain.internal.OutputCleaningCompiler.execute(OutputCleaningCompiler.java:26)
	at org.gradle.language.nativeplatform.internal.incremental.IncrementalNativeCompiler.doCleanIncrementalCompile(IncrementalNativeCompiler.java:96)
	at org.gradle.language.nativeplatform.internal.incremental.IncrementalNativeCompiler.execute(IncrementalNativeCompiler.java:74)
	at org.gradle.language.nativeplatform.internal.incremental.IncrementalNativeCompiler.execute(IncrementalNativeCompiler.java:37)
	at org.gradle.nativeplatform.internal.BuildOperationLoggingCompilerDecorator.execute(BuildOperationLoggingCompilerDecorator.java:38)
	at org.gradle.nativeplatform.internal.BuildOperationLoggingCompilerDecorator.execute(BuildOperationLoggingCompilerDecorator.java:22)
	at org.gradle.language.nativeplatform.tasks.AbstractNativeCompileTask.doCompile(AbstractNativeCompileTask.java:115)
	at org.gradle.language.nativeplatform.tasks.AbstractNativeCompileTask.compile(AbstractNativeCompileTask.java:107)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:243)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:230)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 49 more
Caused by: org.gradle.nativeplatform.toolchain.internal.CommandLineToolInvocationFailure: Objective-C compiler failed while compiling BTimer.m.
	at org.gradle.nativeplatform.toolchain.internal.DefaultCommandLineToolInvocationWorker.execute(DefaultCommandLineToolInvocationWorker.java:83)
	at org.gradle.nativeplatform.toolchain.internal.DefaultCommandLineToolInvocationWorker.execute(DefaultCommandLineToolInvocationWorker.java:30)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$OperationHolder.run(DefaultBuildOperationQueue.java:110)
	at org.gradle.internal.concurrent.ExecutorPolicy$PropagateFailures.onExecute(ExecutorPolicy.java:76)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)


BUILD FAILED
```

**Comment by confile** [comment]
@advayDev1 Here is a more detailed error.

**Comment by brunobowden** [comment]
Does the following path exist on your local system:

    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk

Did you install Xcode is any unusual location?

**Comment by confile** [comment]
No it does not exist. Is it a problem that I use the xcode-beta version?

**Comment by confile** [comment]
I reinstalled the non beta version of Xcode not the path does exist.

**Comment by confile** [comment]
Solved my using Xcode instead of Xcode beta.

**Comment by brunobowden** [comment]
We'll pay more attention to this as the beta finalizes. Hopefully the final
version doesn't move the location of the libraries.

**Comment by confile** [comment]
@brunobowden Xcode 6.4 final is out since 30. June, i.e., yesterday.

**Comment by brunobowden** [comment]
And it works correctly with Xcode 6.4 final?

**Comment by confile** [comment]
No raised this issue: https://github.com/j2objc-contrib/j2objc-gradle/issues/261
