### ISSUE TITLE
org.gradle.api.UnknownTaskException: Task with path 'releaseTestJ2objcExecutable' not found in project ':testProject8' - Flaky integration test on JDK 8 Travis - 

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#374]
Flaky integration test on JDK 8 Travis

Example (may be pruned): https://travis-ci.org/j2objc-contrib/j2objc-gradle/jobs/76505996

Dump:
```
Using worker: worker-linux-docker-126909fb.prod.travis-ci.org:travis-linux-6

Build system information
Build language: groovy
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"

$ git clone --depth=50 git://github.com/j2objc-contrib/j2objc-gradle.git j2objc-contrib/j2objc-gradle
Cloning into 'j2objc-contrib/j2objc-gradle'...
remote: Counting objects: 868, done.
remote: Compressing objects: 100% (312/312), done.
remote: Total 868 (delta 358), reused 803 (delta 305), pack-reused 0
Receiving objects: 100% (868/868), 231.07 KiB | 0 bytes/s, done.
Resolving deltas: 100% (358/358), done.
Checking connectivity... done.
$ cd j2objc-contrib/j2objc-gradle
$ git fetch origin +refs/pull/373/merge:
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 17 (delta 8), reused 15 (delta 7), pack-reused 0
Unpacking objects: 100% (17/17), done.
From git://github.com/j2objc-contrib/j2objc-gradle
 * branch            refs/pull/373/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD

This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
$ jdk_switcher use oraclejdk8
Switching to Oracle JDK8 (java-8-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-8-oracle
$ export TERM=dumb
$ java -Xmx32m -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_31
$ ./gradlew wrapper
Downloading https://services.gradle.org/distributions/gradle-2.4-all.zip
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /home/travis/.gradle/wrapper/dists/gradle-2.4-all/6r4uqcc6ovnq6ac6s0txzcpc0/gradle-2.4-all.zip to /home/travis/.gradle/wrapper/dists/gradle-2.4-all/6r4uqcc6ovnq6ac6s0txzcpc0
Set executable permissions for: /home/travis/.gradle/wrapper/dists/gradle-2.4-all/6r4uqcc6ovnq6ac6s0txzcpc0/gradle-2.4/bin/gradle
Download https://plugins.gradle.org/m2/com/gradle/publish/plugin-publish-plugin/0.9.0/plugin-publish-plugin-0.9.0.pom
Download https://plugins.gradle.org/m2/commons-io/commons-io/1.4/commons-io-1.4.pom
Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/7/commons-parent-7.pom
Download https://plugins.gradle.org/m2/org/apache/apache/4/apache-4.pom
Download https://plugins.gradle.org/m2/com/google/guava/guava/18.0/guava-18.0.pom
Download https://plugins.gradle.org/m2/com/google/guava/guava-parent/18.0/guava-parent-18.0.pom
Download https://plugins.gradle.org/m2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
Download https://plugins.gradle.org/m2/oauth/signpost/oauth-signpost/1.2.1.2/oauth-signpost-1.2.1.2.pom
Download https://plugins.gradle.org/m2/oauth/signpost/signpost-commonshttp4/1.2.1.2/signpost-commonshttp4-1.2.1.2.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.2.2/httpcore-4.2.2.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-core/4.2.2/httpcomponents-core-4.2.2.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/project/6/project-6.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.2.2/httpclient-4.2.2.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-client/4.2.2/httpcomponents-client-4.2.2.pom
Download https://plugins.gradle.org/m2/com/google/code/gson/gson/2.2.4/gson-2.2.4.pom
Download https://plugins.gradle.org/m2/oauth/signpost/signpost-core/1.2.1.2/signpost-core-1.2.1.2.pom
Download https://plugins.gradle.org/m2/commons-codec/commons-codec/1.3/commons-codec-1.3.pom
Download https://plugins.gradle.org/m2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/5/commons-parent-5.pom
Download https://plugins.gradle.org/m2/commons-codec/commons-codec/1.6/commons-codec-1.6.pom
Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/22/commons-parent-22.pom
Download https://plugins.gradle.org/m2/org/apache/apache/9/apache-9.pom
Download https://plugins.gradle.org/m2/com/gradle/publish/plugin-publish-plugin/0.9.0/plugin-publish-plugin-0.9.0.jar
Download https://plugins.gradle.org/m2/commons-io/commons-io/1.4/commons-io-1.4.jar
Download https://plugins.gradle.org/m2/com/google/guava/guava/18.0/guava-18.0.jar
Download https://plugins.gradle.org/m2/oauth/signpost/signpost-commonshttp4/1.2.1.2/signpost-commonshttp4-1.2.1.2.jar
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.2.2/httpcore-4.2.2.jar
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.2.2/httpclient-4.2.2.jar
Download https://plugins.gradle.org/m2/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
Download https://plugins.gradle.org/m2/oauth/signpost/signpost-core/1.2.1.2/signpost-core-1.2.1.2.jar
Download https://plugins.gradle.org/m2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
Download https://plugins.gradle.org/m2/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
:wrapper

BUILD SUCCESSFUL

Total time: 44.539 secs
$ ./gradlew dependencies
:dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

archives - Configuration for archive artifacts.
No dependencies

compile - Compile classpath for source set 'main'.
No dependencies

default - Configuration for default artifacts.
No dependencies

runtime - Runtime classpath for source set 'main'.
No dependencies

testCompile - Compile classpath for source set 'test'.
No dependencies

testRuntime - Runtime classpath for source set 'test'.
No dependencies

BUILD SUCCESSFUL

Total time: 7.093 secs
$ ./gradlew assemble
:compileJava UP-TO-DATE
:compileGroovy
:processResources
:classes
:jar
:groovydoc
:publishPluginGroovyDocsJar
:publishPluginJar
:javadoc UP-TO-DATE
:publishPluginJavaDocsJar
:assemble

BUILD SUCCESSFUL

Total time: 38.615 secs

The command "./gradlew assemble" exited with 0.
$ ./gradlew build
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:groovydoc UP-TO-DATE
:publishPluginGroovyDocsJar UP-TO-DATE
:publishPluginJar UP-TO-DATE
:javadoc UP-TO-DATE
:publishPluginJavaDocsJar UP-TO-DATE
:assemble UP-TO-DATE
:compileTestJava UP-TO-DATE
:compileTestGroovy
:processTestResources
:testClasses
:test

com.github.j2objccontrib.j2objcgradle.MultiProjectTest > twoProjectsWithDependsOnJ2objcLib_Works FAILED
    org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':testProject9'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:487)
        at org.gradle.api.internal.project.AbstractProject.evaluationDependsOn(AbstractProject.java:555)
        at org.gradle.api.internal.project.AbstractProject.evaluationDependsOnChildren(AbstractProject.java:538)
        at org.gradle.api.Project$evaluationDependsOnChildren$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at com.github.j2objccontrib.j2objcgradle.MultiProjectTest.twoProjectsWithDependsOnJ2objcLib_Works(MultiProjectTest.groovy:67)

        Caused by:
        org.gradle.api.GradleException: Could not determine the dependencies of task ':testProject8:j2objcTestRelease'.
            at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.resolve(CachingTaskDependencyResolveContext.java:65)
            at org.gradle.api.internal.tasks.AbstractTaskDependency.getDependencies(AbstractTaskDependency.java:27)
            at org.gradle.api.internal.tasks.DefaultTaskContainer$1.getNodeValues(DefaultTaskContainer.java:195)
            at org.gradle.api.internal.tasks.DefaultTaskContainer$1.getNodeValues(DefaultTaskContainer.java:193)
            at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmpyEdges.getNodeValues(CachingDirectedGraphWalker.java:200)
            at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:112)
            at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:64)
            at org.gradle.api.internal.tasks.DefaultTaskContainer.realize(DefaultTaskContainer.java:193)
            at org.gradle.api.internal.tasks.TaskContainerInternal$realize.call(Unknown Source)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
            at com.github.j2objccontrib.j2objcgradle.MultiProjectTest$_twoProjectsWithDependsOnJ2objcLib_Works_closure1.doCall(MultiProjectTest.groovy:62)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:483)
            at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
            at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
            at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
            at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
            at groovy.lang.Closure.call(Closure.java:423)
            at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
            at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
            at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:87)
            at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
            at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
            at com.sun.proxy.$Proxy18.afterEvaluate(Unknown Source)
            at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
            ... 9 more

            Caused by:
            org.gradle.api.UnknownTaskException: Task with path 'releaseTestJ2objcExecutable' not found in project ':testProject8'.
                at org.gradle.api.internal.tasks.DefaultTaskContainer.getByPath(DefaultTaskContainer.java:167)
                at org.gradle.api.internal.tasks.DefaultTaskContainer.resolveTask(DefaultTaskContainer.java:161)
                at org.gradle.api.internal.tasks.DefaultTaskDependency.resolve(DefaultTaskDependency.java:80)
                at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:86)
                at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmpyEdges.getNodeValues(CachingDirectedGraphWalker.java:200)
                at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:112)
                at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:64)
                at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.doResolve(CachingTaskDependencyResolveContext.java:74)
                at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.resolve(CachingTaskDependencyResolveContext.java:63)
                ... 37 more

94 tests completed, 1 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/travis/build/j2objc-contrib/j2objc-gradle/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 8.901 secs

The command "./gradlew build" exited with 1.

Done. Your build exited with 1.
```

**Comment by advayDev1** [comment]
As long as Android is Java 7, I'd rather not worry about this.

**Comment by brunobowden** [comment]
I'm closing this - we'll reopen once Java 8 is considered for Android.
