### ISSUE TITLE
Incremental Compile fails with error: failed batch processing sources

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#447]
Here is what I did:

1. ``gradle shared:build```
2. Changes in TestClass.java
3. ``gradle shared:build```  

This leads to the following error: 
```
:shared:j2objcTranslate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shared:j2objcTranslate'.
> Command Line Failed:
  /Applications/J2Objc/j2objc-0.9.8b/j2objc -d /Users/mg/Downloads/Majestella/shared/build/j2objcSrcGen -sourcepath /Users/mg/Downloads/Majestella/shared/src/main/java:/Users/mg/Downloads/Majestella/shared/build/translationExtraction:/Users/mg/Downloads/Majestella/shared/build/source/apt:/Users/mg/Downloads/Majestella/shared/build/source/base:/Users/mg/Downloads/Majestella/shared/src/test/java -classpath /Users/mg/Downloads/Majestella/shared/lib/json-20140107.jar:/Users/mg/Downloads/Majestella/shared/lib/javax.inject-1.jar:/Users/mg/Downloads/Majestella/shared/lib/auto-factory-1.0-beta2.jar:/Users/mg/Downloads/Majestella/shared/lib/auto-service-1.0-rc2.jar:/Users/mg/Downloads/Majestella/shared/lib/javawriter-2.5.1.jar:/Users/mg/Downloads/Majestella/shared-prebuild/build/libs/shared-prebuild-1.0.jar:/Applications/J2Objc/j2objc-0.9.8b/lib/j2objc_annotations.jar:/Applications/J2Objc/j2objc-0.9.8b/lib/j2objc_guava.jar:/Applications/J2Objc/j2objc-0.9.8b/lib/j2objc_junit.jar:/Applications/J2Objc/j2objc-0.9.8b/lib/jre_emul.jar:/Applications/J2Objc/j2objc-0.9.8b/lib/javax.inject-1.jar:/Applications/J2Objc/j2objc-0.9.8b/lib/jsr305-3.0.0.jar:/Applications/J2Objc/j2objc-0.9.8b/lib/mockito-core-1.9.5.jar:/Users/mg/Downloads/Majestella/shared/build/classes --no-package-directories --prefixes prefixes.properties -use-arc --doc-comments --generate-deprecated /Users/mg/Downloads/Majestella/shared/build/source/apt/generated/BPlaceTokenRegistryImpl.java /Users/mg/Downloads/Majestella/shared/build/source/apt/generated/ProxyModule.java /Users/mg/Downloads/Majestella/shared/build/source/apt/majestella/core/app/serviceSelection/ServiceSelectionPresenterMyProxyImpl.java /Users/mg/Downloads/Majestella/shared/src/main/java/TestClass.java
  Working Dir:
  /Users/mg/Downloads/Majestella/shared
  Cause:
  org.gradle.process.internal.ExecException: Process 'command '/Applications/J2Objc/j2objc-0.9.8b/j2objc'' finished with non-zero exit value 1
  Standard Output:
  
  Error Output:
  1. ERROR: failed
  2. ERROR: failed
  3. ERROR: failed
  4. ERROR: failed
  5. ERROR: failed
  6. ERROR: failed
  7. ERROR: failed
  8. ERROR: failed
  9. ERROR: failed
  10. ERROR: failed
  11. ERROR: failed
  12. ERROR: failed
  12 problems (12 errors)
  error: failed batch processing sources


* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':shared:j2objcTranslate'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:208)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:186)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:111)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher$6.run(DefaultGradleLauncher.java:174)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:47)
	at org.gradle.initialization.DefaultGradleLauncher.runBuildOperation(DefaultGradleLauncher.java:189)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:171)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:35)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:104)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.runRootBuildOperation(DefaultGradleLauncher.java:184)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:93)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:27)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:72)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:44)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: org.gradle.api.InvalidUserDataException: Command Line Failed:
/Applications/J2Objc/j2objc-0.9.8b/j2objc -d /Users/mg/Downloads/Majestella/shared/build/j2objcSrcGen -sourcepath /Users/mg/Downloads/Majestella/shared/src/main/java:/Users/mg/Downloads/Majestella/shared/build/translationExtraction:/Users/mg/Downloads/Majestella/shared/build/source/apt:/Users/mg/Downloads/Majestella/shared/build/source/base:/Users/mg/Downloads/Majestella/shared/src/test/java -classpath /Users/mg/Downloads/Majestella/shared/lib/json-20140107.jar:/Users/mg/Downloads/Majestella/shared/lib/javax.inject-1.jar:/Users/mg/Downloads/Majestella/shared/lib/auto-factory-1.0-beta2.jar:/Users/mg/Downloads/Majestella/shared/lib/auto-service-1.0-rc2.jar:/Users/mg/Downloads/Majestella/shared/lib/javawriter-2.5.1.jar:/Users/mg/Downloads/Majestella/shared-prebuild/build/libs/shared-prebuild-1.0.jar:/Applications/J2Objc/j2objc-0.9.8b/lib/j2objc_annotations.jar:/Applications/J2Objc/j2objc-0.9.8b/lib/j2objc_guava.jar:/Applications/J2Objc/j2objc-0.9.8b/lib/j2objc_junit.jar:/Applications/J2Objc/j2objc-0.9.8b/lib/jre_emul.jar:/Applications/J2Objc/j2objc-0.9.8b/lib/javax.inject-1.jar:/Applications/J2Objc/j2objc-0.9.8b/lib/jsr305-3.0.0.jar:/Applications/J2Objc/j2objc-0.9.8b/lib/mockito-core-1.9.5.jar:/Users/mg/Downloads/Majestella/shared/build/classes --no-package-directories --prefixes prefixes.properties -use-arc --doc-comments --generate-deprecated /Users/mg/Downloads/Majestella/shared/build/source/apt/generated/BPlaceTokenRegistryImpl.java /Users/mg/Downloads/Majestella/shared/build/source/apt/generated/ProxyModule.java /Users/mg/Downloads/Majestella/shared/build/source/apt/majestella/core/app/serviceSelection/ServiceSelectionPresenterMyProxyImpl.java /Users/mg/Downloads/Majestella/shared/src/main/java/TestClass.java
Working Dir:
/Users/mg/Downloads/Majestella/shared
Cause:
org.gradle.process.internal.ExecException: Process 'command '/Applications/J2Objc/j2objc-0.9.8b/j2objc'' finished with non-zero exit value 1
Standard Output:

Error Output:
1. ERROR: failed
2. ERROR: failed
3. ERROR: failed
4. ERROR: failed
5. ERROR: failed
6. ERROR: failed
7. ERROR: failed
8. ERROR: failed
9. ERROR: failed
10. ERROR: failed
11. ERROR: failed
12. ERROR: failed
12 problems (12 errors)
error: failed batch processing sources

	at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectExec(Utils.groovy:567)
	at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTask.translate(TranslateTask.groovy:245)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:243)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:230)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 58 more
Caused by: org.gradle.process.internal.ExecException: Process 'command '/Applications/J2Objc/j2objc-0.9.8b/j2objc'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:366)
	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
	at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:165)
	at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:792)
	at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:788)
	at org.gradle.api.Project$exec$4.call(Unknown Source)
	at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectExec(Utils.groovy:550)
	... 66 more


BUILD FAILED
```

**Comment by brunobowden** [comment]
If you copy and paste the command line
(/Applications/J2Objc/j2objc-0.9.8b/j2objc....),
does it fail in the same way?

Also, are you running a custom build of j2objc - I'm looking at the "b" on
the end of the version name. Try the release version of 0.9.8 and 0.9.7.

**Comment by brunobowden** [comment]
Assuming you get this error by running the command line with a release
version of j2objc, with very limited output, then this is an issue for
j2objc. So discuss it on j2objc-discuss. It should be giving more
descriptive error messages than this.

**Comment by brunobowden** [comment]
@confile - you should only have one bug open at a time. Also, it's best to reference issues that are related. In this case, you should close this bug and then at the same time reference https://github.com/google/j2objc/issues/598

**Comment by confile** [comment]
> If you copy and paste the command line
(/Applications/J2Objc/j2objc-0.9.8b/j2objc....),
does it fail in the same way?

This is interesting when I copy the command to the command line I get: 

```
translating /Users/mg/Downloads/Majestella/shared/build/source/apt/generated/BPlaceTokenRegistryImpl.java
translating /Users/mg/Downloads/Majestella/shared/build/source/apt/generated/ProxyModule.java
translating /Users/mg/Downloads/Majestella/shared/build/source/apt/majestella/core/app/serviceSelection/ServiceSelectionPresenterMyProxyImpl.java
translating /Users/mg/Downloads/Majestella/shared/src/main/java/TestClass.java
Translated 4 files: 0 errors, 0 warnings
Translated 8 methods as functions
```
This works well. So it is definitively a plugin issue. I will close the other issue. 

> Also, are you running a custom build of j2objc - I'm looking at the "b" on
the end of the version name. Try the release version of 0.9.8 and 0.9.7.

@brunobowden It is no custom build. I use the official release 0.9.8.1 I just copied it in the folder 0.9.8b.

**Comment by brunobowden** [comment]
Can you simplify down the failure case.

I think the other issue is still legitimate in that it should produce more
helpful error messages... but definitely update the bug.

**Comment by confile** [comment]
It is not easy to build a small test case out of a big project.

**Comment by brunobowden** [comment]
Understood... but that's often the best way to get others to help you. It
means that you can share the code and we can try it out. Ideally we can add
it to the automated build so that we can ensure whatever issue we fix,
stays fixed. I sometimes spend days to reduce down the test case to
something that I can share with others.

**Comment by confile** [comment]
Does the debug log helps you?

**Comment by brunobowden** [comment]
What's helpful is a small amount of helpful targeted information, not lots of information. So look through the logs yourself and see if you can pick out a small section that looks helpful. For example a few lines where you can say "this seems to indicate that the problem may be XXXX". When you share pages and pages debug logs, it's too much information, that I don't have the time to read through it.

The ideal thing to publicly share the source code for a small test case that shows the problem. Even better, add it as an example to the "systemTests" directory so that we can ensure it stays fixed.

**Comment by confile** [comment]
I am working on separating the error in a test project.

**Comment by confile** [comment]
The problem is that this issue occurred when I switch from j2obj 0.9.7 to 0.9.8. 

@advayDev1 Do you have any idea on this?

**Comment by brunobowden** [comment]
0.9.8 introduced some more annotation support. Try and see if you can get a
command that works in 0.9.7 and fails in 0.9.8.

New annotation support:
J2ObjCIncompatible
LoopTranslationProperty
RetainedLocalRef

**Comment by confile** [comment]
May be this helps @brunobowden : 

```
Error Output:
1. ERROR: failed
1 problem (1 error)
error: failed batch processing sources

	at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectExec(Utils.groovy:567)
	at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTask.translate(TranslateTask.groovy:245)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:243)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:230)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 58 more
Caused by: org.gradle.process.internal.ExecException: Process 'command '/Applications/J2Objc/j2objc-0.9.8.1/j2objc'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:366)
	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
	at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:165)
	at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:792)
	at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:788)
	at org.gradle.api.Project$exec$4.call(Unknown Source)
	at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectExec(Utils.groovy:550)
	... 66 more
```

**Comment by brunobowden** [comment]
That's better than the whole log:
1) Your using "0.9.8.1" so it's clearer what it is
2) It's a simpler failure message.

Can you share the code example publicly? Also the command line helps.
Though in this case, just focus on sharing a public example. A simple code
example will help a great deal. Ideally only a few files and less than 100
lines of code.

**Comment by confile** [comment]
@brunobowden Well I am still in the process of reducing the code. I have the feeling that it has something to do with the annotation processor. Hope we can get this fixed.

**Comment by confile** [comment]
@brunobowden I created a test project here: https://github.com/confile/j2objc-test

To reproduce the error just do: 

1. ``gradle shared:clean gradle shared:j2objcTranslate``
2. Change something.
3. ``gradle shared:j2objcTranslate``

Note: If you change variables sometimes recompile works for whatever reason. Then just do some more changes.

**Comment by confile** [comment]
@advayDev1 Since Bruno is on vacation could you please take a look at this issue?

**Comment by advayDev1** [comment]
first do a clean.
then run just j2objcTranslate.  does that work?

if it does not, try to run the command line it will dump out.

**Comment by confile** [comment]
@advayDev1 I can do clean and translate. That works but I cannot do: clean, translate, change, translate. This is the recommended case.

**Comment by confile** [comment]
@brunobowden any progress on this issue?

**Comment by advayDev1** [comment]
This is an internal error in the j2objc tool from what your error shows.  There's nothing @j2objc-contrib/owners can do at this moment and therefore no progress.

If this is still a problem, you need to get and share an exact j2objc command line (use --info on gradlew) and I will reopen.
