### ISSUE TITLE
Could not find property 'binaries' on project ':base' - Gradle 2.9-rc-1 regression

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#568]
This works fine with Gradle 2.8 but fails with with 2.9-rc-1. It appears to be an intentional breakage that you'll have to deal with:

*The binaries container is no longer bridged into the regular plugin space, and is now only visible to rules via model. The binaries project extension has been removed.*

https://docs.gradle.org/release-candidate/release-notes#changes-to-the-experimental-integration-between-the-java-software-model-and-the-java-plugins

Caused by: groovy.lang.MissingPropertyException: Could not find property 'binaries' on project ':base'.
	at org.gradle.api.internal.AbstractDynamicObject.propertyMissingException(AbstractDynamicObject.java:43)
	at org.gradle.api.internal.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:35)
	at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:97)
	at org.gradle.api.internal.project.DefaultProject_Decorated.getProperty(Unknown Source)
	at com.github.j2objccontrib.j2objcgradle.NativeCompilation$_apply_closure2.doCall(NativeCompilation.groovy:258)
	at com.github.j2objccontrib.j2objcgradle.NativeCompilation.apply(NativeCompilation.groovy:127)
	at com.github.j2objccontrib.j2objcgradle.J2objcConfig.configureNativeCompilation(J2objcConfig.groovy:827)
	at com.github.j2objccontrib.j2objcgradle.J2objcConfig.finalConfigure(J2objcConfig.groovy:731)
	at build_15mxmbvxw4tw5xblism0ohhl9$_run_closure6.doCall(/Users/brunobowden/dev/taptap/base/build.gradle:84)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
	at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
	at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_15mxmbvxw4tw5xblism0ohhl9.run(/Users/brunobowden/dev/taptap/base/build.gradle:56)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 95 more

**Comment by brunobowden** [comment]
cc @eapache

**Comment by advayDev1** [comment]
@brunobowden we're now at the point of no return i think.
we have to finish that discussion we put off last Oct/Nov about fully migrating to the "3.0" way of doing things, using Models and Rules for all of the plugin.  That is a substantial rewrite that I don't believe either of us have time to do right now

**Comment by brunobowden** [comment]
@advayDev1 - yeah, this is unfortunate. I would like to get some others involved to help out on something like this. It'll be a while before 2.9 is common place, so we'll defer the discussion for now.

Here's the updated link for the 2.9 release notes: https://docs.gradle.org/2.9/release-notes#the-binaries-container-is-no-longer-accessible-as-a-project-extension

**Comment by sriharim25** [comment]
any updates on supporting gradle 2.9+?

**Comment by patjackson52** [comment]
This is issue is probably a show stopper for people trying out j2objc.  Android developers are using more recent versions of gradle

**Comment by palindrajit** [comment]
any update on supporting on current release. Is there any workaround? The workaround which is available https://github.com/j2objc-contrib/j2objc-gradle/issues/621 is not working with latest android plugin and gradle plugin 1.0.2

**Comment by kpgalligan** [comment]
Adding this:

System.properties['com.android.build.gradle.overrideVersionCheck'] = 'true'

to the root build file, and changing the gradle wrapper to 2.8 still works.

gradle/wrapper/gradle-wrapper.properties

Add/change

distributionUrl=https\://services.gradle.org/distributions/gradle-2.8-all.zip

**Comment by andreas-** [comment]
+1

**Comment by Bkrickl** [comment]
+1
